# Generated by readme.cr

require "./spec_helper"

describe "README.md" do
  it "Usage" do
    # require "comment-spec"
    
    ( CommentSpec.parse "1 + 2 # => 3" ).to_s.should eq( "( 1 + 2 ).should eq( 3 )" )
    ( CommentSpec.parse "value # => 2016-03-31 12:36:21" ).to_s.should eq( "( value ).should eq( Time.parse(\"2016-03-31 12:36:21\", \"%F %T\") )" )
    ( CommentSpec.parse "v[10] # raises IndexError" ).to_s.should eq( "expect_raises(IndexError) { v[10] }" )
    ( CommentSpec.parse "value # => #<XXX>" ).to_s.should eq( "( value ).class.to_s.should eq( \"XXX\" )" )
    CommentSpec::Parser.parse("foo \"a # => b\"")
  end
end
